### ISSUE TITLE
Remove private path information

### ISSUE THREAD

**Issue by JuliusWelzel** [MMarieSchuckart/EXNAT-1#1]
https://github.com/MMarieSchuckart/EXNAT-1/blob/a7aaf08e1f785ca47a55f44aa0e04791eb891804/Analysis/word%20frequencies/calculate_word_frequencies.py#L34

This line makes the directory config of your machine public, you probably want to use a more dynamic approach to specify the path for example as done [here](https://neurogeriatricskiel.github.io/NGMT/examples/basic_01_load_Data/#read-the-raw-data-and-metadata-into-python).

**Comment by MMarieSchuckart** [comment]
Good catch, thank you! Are you procrastinating with my repo? 😄
